# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = ['ruby']
# 
# [[plugins]]
# repo = 'shougo/deoplete-rct'
# depends = ['deoplete.nvim']
# on_ft = ['ruby']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


