# colorschemeの設定
[[plugins]]
#repo = 'NLKNguyen/papercolor-theme'
repo = 'morhetz/gruvbox'
hook_add = '''
  "set background=light
  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme gruvbox
'''

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'

# j, k移動高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
  nmap j <Plug>(accelerated_jk_gj)
  nmap k <Plug>(accelerated_jk_gk)
'''

# カーソル移動高速化
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " Do not rely on default bidings.
  let g:EasyMotion_do_mapping = 0
  " Turn on case sensitive feature
  let g:EasyMotion_smartcase = 1

  nmap s <Plug>(easymotion-overwin-f2)
  xmap s <Plug>(easymotion-overwin-f2)
  omap z <Plug>(easymotion-overwin-f2)

  nmap g/ <Plug>(easymotion-sn)
  xmap g/ <Plug>(easymotion-sn)
  omap g/ <Plug>(easymotion-tn)
'''

# マルチカーソル
# [[plugins]]
# repo = 'terryma/vim-multiple-cursors'

# /検索強化
# [[plugins]]
# repo = 'osyo-manga/vim-anzu'
# hook_add = '''
#   nmap n nzz<Plug>(anzu-update-search-status)
#   nmap N Nzz<Plug>(anzu-update-search-status)
#   nmap * <Plug>(anzu-star)
#   nmap # <Plug>(anzu-sharp)
#   nmap <silent> <ESC><ESC> :<C-u>nohlsearch<CR><Plug>(anzu-clear-search-status)
# '''

# f検索強化
[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
  let g:clever_f_ignore_case = 1        " 小文字を入力した場合、大文字小文字区別しない
  let g:clever_f_smart_case = 1         " 大文字を入力したら大文字のみ
  let g:clever__f_fix_key_direction = 1 " fで右、Fで左検索
  let g:clever_f_not_overwrites_standard_mappings = 1 " tはtabに使いたいので標準マッピングにしない
  nmap f <Plug>(clever-f-f)
  xmap f <Plug>(clever-f-f)
  omap f <Plug>(clever-f-f)
  nmap F <Plug>(clever-f-F)
  xmap F <Plug>(clever-f-F)
  omap F <Plug>(clever-f-F)
'''

# :e sudo:%
# [[plugins]]
# repo = 'vim-scripts/sudo.vim'

# gitの変更箇所を左にマーク表示する
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  set diffopt+=vertical
  :command Gs Gstatus
  :command Ga Gwrite
  :command Gc Gcommit-v
  :command Gd Gdiff
  :command Gm Gmerge
  :command Gb Gblame
'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'vim-fugitive']
hook_add = '''
  let g:airline_powerline_fonts = 1
  set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# rubyとかvimscriptのifとかの終了を補完してくれる
[[plugins]]
repo = 'cohama/lexima.vim'

# cursorの位置でfiletypeを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
hook_add = '''
  " コンテキストの外側をコメントカラーにしない
  let g:precious_enable_switchers = {
    \   "*" : {
    \       "outer_region" : 0
    \   }
    \}
'''

[[plugins]]
repo = 'shougo/context_filetype.vim'

