# colorschemeの設定
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  "set background=light
  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme gruvbox
'''

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# j, k移動高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
  nmap j <Plug>(accelerated_jk_gj)
  nmap k <Plug>(accelerated_jk_gk)
'''

# カーソル移動高速化
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " Do not rely on default bidings.
  let g:EasyMotion_do_mapping = 0
  " Turn on case sensitive feature
  let g:EasyMotion_smartcase = 1

  nmap s <Plug>(easymotion-overwin-f2)
  xmap s <Plug>(easymotion-overwin-f2)
  omap z <Plug>(easymotion-overwin-f2)

  nmap g/ <Plug>(easymotion-sn)
  xmap g/ <Plug>(easymotion-sn)
  omap g/ <Plug>(easymotion-tn)
'''

# gitの変更箇所を左にマーク表示する
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
depends = ['vim-rhubarb']
hook_add = '''
  set diffopt+=vertical
  :command Gs Gstatus
  :command Ga Gwrite
  :command Gc Gcommit-v
  :command Gd Gdiff
  :command Gm Gmerge
  :command Gb Gblame
  :command Gh Gbrowse
'''

[[plugins]]
repo    = 'tpope/vim-rhubarb'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'vim-fugitive', 'ale']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#ale#error_symbol = '❌'
  let g:airline#extensions#ale#warning_symbol = '⚠️ '
  set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# rubyとかvimscriptのifとかの終了を補完してくれる
[[plugins]]
repo = 'cohama/lexima.vim'

# いろんなもののハイライト
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = ['csv']
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_fixers = {
        \ 'javascript': ['eslint'],
        \ 'typescript': ['eslint'],
        \ 'vue': ['eslint'],
        \ 'ruby': ['rubocop']
        \ }
  let g:ale_fix_on_save = 1
'''

# コメントの切り替えをgccでできるようになる
[[plugins]]
repo = 'tpope/vim-commentary'

# 選択文字をSで囲んだり、囲み文字切り替えできるようになる
[[plugins]]
repo = 'tpope/vim-surround'

