[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['csv']
hook_add = '''
  autocmd BufRead,BufNewFile *.csv setfiletype csv
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'vue']

